"""habits

Revision ID: 460ae1e5c3b6
Revises: ddc9a3d5ce01
Create Date: 2024-12-30 16:28:24.030557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ae1e5c3b6'
down_revision: Union[str, None] = 'ddc9a3d5ce01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
