"""added password removed role

Revision ID: 5a99f26fa5f1
Revises: cf80cbd3f7ce
Create Date: 2024-12-30 11:18:16.611791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a99f26fa5f1'
down_revision: Union[str, None] = 'cf80cbd3f7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add username column as nullable
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    
    # Update existing rows with a default username
    op.execute("UPDATE users SET username = 'default_username' WHERE username IS NULL")
    
    # Make username column non-nullable
    op.alter_column('users', 'username', nullable=False)
    
    # Add password column as nullable
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    
    # Update existing rows with a default password (you should change this in production!)
    op.execute("UPDATE users SET password = 'change_me' WHERE password IS NULL")
    
    # Make password column non-nullable
    op.alter_column('users', 'password', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
